version: '3.8'

services:
  api:
    build: .
    container_name: processamento-mensagens-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./templates:/app/templates
    environment:
      - DEBUG=True
      - API_HOST=0.0.0.0
      - API_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: processamento-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped
    profiles:
      - production